### ISSUE TITLE
Cloning probability error?

### ISSUE THREAD

**Issue by dominusmi** [FragileTech/FractalAI#102]
Hello!

I believe there might be an error in the cloning probability, both in the paper and the code.

![image](https://user-images.githubusercontent.com/11195159/72203372-5d51ac00-346b-11ea-8dd1-509c34102132.png)

I think the third equation should be <img src="https://latex.codecogs.com/gif.latex?\frac{VR_k-VR_i}{VR_k}" />, since we know <img src="https://latex.codecogs.com/gif.latex?VR_k>VR_i" />

With your current probability, it will very likely be greater than 1, for instance if <img src="https://latex.codecogs.com/gif.latex?VR_k=1.4,VR_i=0.7"/> will give probability = 1.
On the other hand, using the <img src="https://latex.codecogs.com/gif.latex?VR_k"/> as denominator, we get p=0.5.

Was this an error, or was it an intentional choice to bias the probability upwards, and if so why?

**Comment by sergio-hcsoft** [comment]
The equation is right as it is. If the other walkers' virtual reward were +30% better than yours, you would clone with probability 0.3, but if it were more than double of yours, then it is +100% better and then you will just do clone, without flipping any coin. It is the same case where his reward is lower and you get a negative prob. of cloning, just meaning you won't clone.

After all, you get a "clone prob." P and a random number R in [0, 1] and the code just clone if (R<P), no problem if P is whatever real number you get, it always makes sense, but some people feel uncomfortable with this. Just clip probabilities into [0, 1] to recover peace of mind!

**Comment by dominusmi** [comment]
Alright thank you for the answer :)
